<?
	$data=array(
		'id'=>1,
		'name'=>"Тексты",
		'fields'=>array(		
			'name'=>array(
				'russian_name'=>'Заголовок',
				'is_active'=>true,
				'is_always'=>true,
			),
			'pid'=>array(
				'russian_name'=>'Предок',
				'is_active'=>true,
				'is_always'=>true,
			),
			'short_text'=>array(
				'russian_name'=>'Краткое содержимое',
				'is_active'=>false,
				'is_always'=>false,
			),
			'text'=>array(
				'russian_name'=>'Полное содержимое',
				'is_active'=>true,
				'is_always'=>true,
			),
			'order'=>array(
				'russian_name'=>'Порядок',
				'is_active'=>true,
				'is_always'=>false,
			),
			'is_show'=>array(
				'russian_name'=>'Показать',
				'is_active'=>true,
				'is_always'=>true,
			),
			'date'=>array(
				'russian_name'=>'Дата',
				'is_active'=>false,
				'is_always'=>false,
			),
			'file'=>array(
				'russian_name'=>'Файл',
				'is_active'=>false,
				'is_always'=>false,
			),
			'gallery_id'=>array(
				'russian_name'=>'Галерея',
				'is_active'=>false,
				'is_always'=>false,
			),
			'url'=>array(
				'russian_name'=>'URL',
				'is_active'=>true,
				'is_always'=>true,
			),
			'h1'=>array(
				'russian_name'=>'h1',
				'is_active'=>true,
				'is_always'=>false,
			),
			'meta_title'=>array(
				'russian_name'=>'meta-title',
				'is_active'=>true,
				'is_always'=>false,
			),
			'meta_description'=>array(
				'russian_name'=>'meta-description',
				'is_active'=>true,
				'is_always'=>false,
			),
			'meta_keywords'=>array(
				'russian_name'=>'meta-keywords',
				'is_active'=>true,
				'is_always'=>false,
			),
			'region_rewrite'=>array(
				'russian_name'=>'Разрешить перезапись',
				'is_active'=>false,
				'is_always'=>false,
			),
		),
		'rools'=>array(
			'access'=>true,
			'add'=>true,
			'edit'=>true,
			'delete'=>true,
			'show'=>true,
		),
		'special'=>array(
			'/texts/show_all'=>'Показать все',
		),
		'settings'=>array(
			'module'=>array(
				'name'=>'Конфигурация модуля',
				'data'=>array(
					'is_groups'=>array(
						'name'=>'Разрешать создавать группы',
						'type'=>'checkbox',
						'value'=>true,
					),
				),
			),
		),
		'functions'=>array(
			'popup_level2_menu'=>array(
				'name'=>'Вывод двухуровневого выпадающего меню',
				'params'=>array(
					'name'=>array(
						'name'=>'Заголовок',
						'type'=>'text',
					),
					'root_id'=>array(
						'name'=>'ИД корня',
						'type'=>'text',
					),
				),
			),
		),
	);
?>