<?
	$data=array(
		'id'=>2,
		'name'=>"Пользователи",
		'fields'=>array(
			'login'=>array(
				'russian_name'=>'Логин',
				'is_active'=>true,
				'is_always'=>true,
			),
			'name'=>array(
				'russian_name'=>'Имя',
				'is_active'=>true,
				'is_always'=>true,
			),
			'second_name'=>array(
				'russian_name'=>'Отчество',
				'is_active'=>false,
				'is_always'=>false,
			),
			'third_name'=>array(
				'russian_name'=>'Фамилия',
				'is_active'=>false,
				'is_always'=>false,
			),
			'phone'=>array(
				'russian_name'=>'Телефон',
				'is_active'=>false,
				'is_always'=>false,
			),
			'email'=>array(
				'russian_name'=>'Email',
				'is_active'=>false,
				'is_always'=>false,
			),
			'address'=>array(
				'russian_name'=>'Адрес',
				'is_active'=>false,
				'is_always'=>false,
			),
			'confirm'=>array(
				'russian_name'=>'Строка-подтверждение',
				'is_active'=>false,
				'is_always'=>false,
			),
		),
		'rools'=>array(
			'access'=>true,
			'add'=>true,
			'edit'=>true,
			'delete'=>true,
			'show'=>true,
		),
	);
?>